/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Citizen;

import Business.Citizen.Citizen;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PublicSectorEnterprise;
import Business.Network.Network;
import static com.teamdev.jxbrowser.chromium.ay.c;
import java.awt.CardLayout;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author haroonperveez
 */
public class UpdatePersonalDetails extends javax.swing.JPanel {

    /**
     * Creates new form UpdatePersonalDetails
     */
    JPanel container;
    EcoSystem system;
    Citizen c;
    PublicSectorEnterprise e;
    
    public UpdatePersonalDetails(JPanel container,EcoSystem system,Citizen c) {
        initComponents();
        this.container = container;
        this.system =system;
        this.c= c;
        jComboBox1.setEnabled(false);
        citizenIDTxTField.setText(String.valueOf(c.getCid()));
        
        SimpleDateFormat dtFormat =  new SimpleDateFormat ("MM/dd/yyyy");
        nameTxTField.setText(c.getFirstName());
        lastNameTxtField.setText(c.getLastName());
        dateTxtField.setText(dtFormat.format(c.getDateofBirth()));
        emailIdTextField.setText(c.getEmailAddress());
        if(c.getGender().equalsIgnoreCase("Male")){
            MaleBtn.setSelected(true);
        }
        if(c.getGender().equalsIgnoreCase("Female")){
        
            Female.setSelected(true);
        
        }
        lastNameTxtField.setText(c.getLastName());
        ssnTxtfield.setText(String.valueOf(c.getSsn()));
        phoneNumberTexTField.setText(String.valueOf(c.getContactNumber()));
        userNameTxTFiedl.setText(c.getUserId());
        passwordTxtField.setText(c.getPassword());
        jComboBox1.setSelectedItem(c.getState());
        
        fillCombo();
    }

    
    public void fillCombo(){
        int i =0;
        Network[] arr=new Network[system.getNetworkList().size()];
        for (Network n : system.getNetworkList()) {
            arr[i]=n;
            i++;
        }
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(arr));
        jComboBox1.setSelectedIndex(0);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        userNameTxTFiedl = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        phoneNumberTexTField = new javax.swing.JTextField();
        lastNameTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nameTxTField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ssnTxtfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        citizenIDTxTField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        passwordTxtField = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        dateTxtField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        emailIdTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        MaleBtn = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("User Name:");

        userNameTxTFiedl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTxTFiedlActionPerformed(evt);
            }
        });

        jLabel11.setText("Phone Number:");

        jLabel4.setText("Last Name:");

        jLabel1.setText("First Name :");

        jLabel3.setText("SSN");

        jLabel2.setText("Citizen ID:");

        citizenIDTxTField.setEnabled(false);

        jButton2.setText("<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel7.setText("password:");

        jLabel5.setText("State");

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Date of Birth:");

        jLabel9.setText("Email id:");

        jLabel10.setText("Gender:");

        buttonGroup1.add(MaleBtn);
        MaleBtn.setText("Male");

        buttonGroup1.add(Female);
        Female.setText("Female");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(passwordTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameTxTFiedl, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel9))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(emailIdTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastNameTxtField)
                                    .addComponent(phoneNumberTexTField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ssnTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel5))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(MaleBtn)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(Female))
                                                    .addComponent(dateTxtField)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(nameTxTField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(citizenIDTxTField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(97, 97, 97))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(citizenIDTxTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTxTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(dateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lastNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(MaleBtn)
                    .addComponent(Female))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(emailIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(ssnTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(phoneNumberTexTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(userNameTxTFiedl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(passwordTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel12.setText("Citizen Profile Update");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel12)
                .addGap(61, 61, 61)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(327, 327, 327))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 921, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userNameTxTFiedlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTxTFiedlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTxTFiedlActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            String check = "";
        
        check = utility.Validator.ValidateTextFields(ssnTxtfield,true,3,9,9);
        if(!check.equals("")){JOptionPane.showMessageDialog(null,check,"Alert",JOptionPane.WARNING_MESSAGE);return;}
        check = utility.Validator.ValidateTextFields(nameTxTField,true,0,3,25);
        if(!check.equals("")){JOptionPane.showMessageDialog(null,check,"Alert",JOptionPane.WARNING_MESSAGE);return;}
        check = utility.Validator.ValidateTextFields(lastNameTxtField,true,0,2,25);
        if(!check.equals("")){JOptionPane.showMessageDialog(null,check,"Alert",JOptionPane.WARNING_MESSAGE);return;}
        check = utility.Validator.ValidateTextFields(phoneNumberTexTField,true,3,10,10);
        if(!check.equals("")){JOptionPane.showMessageDialog(null,check,"Alert",JOptionPane.WARNING_MESSAGE);return;}
        check = utility.Validator.ValidateTextFields(dateTxtField,true,2,5,25);
        if(!check.equals("")){JOptionPane.showMessageDialog(null,check,"Alert",JOptionPane.WARNING_MESSAGE);return;}
        if(buttonGroup1.getSelection()==null){
        JOptionPane.showMessageDialog(null,"Select a Gender","Alert",JOptionPane.WARNING_MESSAGE);
        }
        check = utility.Validator.ValidateTextFields(userNameTxTFiedl,true,0,4,25);
        if(!check.equals("")){JOptionPane.showMessageDialog(null,check,"Alert",JOptionPane.WARNING_MESSAGE);return;}
        if(passwordTxtField.getPassword().length<4)
        {check="Password should be atleast 4 characters long!";}
        if(!check.equals("")){JOptionPane.showMessageDialog(null,check,"Alert",JOptionPane.WARNING_MESSAGE);return;}
        
            SimpleDateFormat dtFormat =  new SimpleDateFormat ("MM/dd/yyyy");

            c.setUserId(userNameTxTFiedl.getText());
            c.setPassword(String.valueOf(passwordTxtField.getPassword()));
            c.setContactNumber(Long.parseLong(phoneNumberTexTField.getText()));
            c.setEmailAddress(emailIdTextField.getText());
            c.setFirstName(nameTxTField.getText());
            c.setDateofBirth(dtFormat.parse(dateTxtField.getText()));
            c.setSsn(Long.parseLong(ssnTxtfield.getText()));
            c.setLastName(lastNameTxtField.getText());

            if(MaleBtn.isSelected())
            {
                c.setGender("Male");
            }
            if(Female.isSelected())
            {
                c.setGender("Female");
            }
        } catch (ParseException ex) {
            Logger.getLogger(CitizenRegisterJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(null,"Citizen has been Updated Succesfully");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Female;
    private javax.swing.JRadioButton MaleBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField citizenIDTxTField;
    private javax.swing.JTextField dateTxtField;
    private javax.swing.JTextField emailIdTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastNameTxtField;
    private javax.swing.JTextField nameTxTField;
    private javax.swing.JPasswordField passwordTxtField;
    private javax.swing.JTextField phoneNumberTexTField;
    private javax.swing.JTextField ssnTxtfield;
    private javax.swing.JTextField userNameTxTFiedl;
    // End of variables declaration//GEN-END:variables
}
